name: slide_1_fundamento

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ../../caderno/1_semestre/fund_de_informatica/aula_1 yarn
      - run: ../../caderno/1_semestre/fund_de_informatica/aula_1 yarn build --if-present
        env:
          CI: true
